name: compilar-latex

on:
  push:
    branches:
      - main
      - dev
      - artigo*

jobs:
  build_latex:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/xu-cheng/texlive-full:latest

    steps:
      - uses: actions/checkout@v4

      - name: Compilar LaTeX
        run: |
          cd LaTeX
          latexmk -pdf -interaction=nonstopmode main.tex

      - name: Upload PDF
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: LaTeX/main.pdf

      - name: Resumo
        run: echo "[PDF Compilado](${{ steps.upload.outputs.artifact-url }})" >> $GITHUB_STEP_SUMMARY
 